Changes

diff --git a/scripts/terra_colab_web b/scripts/terra_colab_web
--- a/scripts/terra_colab_web
+++ b/scripts/terra_colab_web
@@ -7,39 +7,39 @@ red=$(tput setaf 1)
 reset=$(tput sgr0)
 
 function usage() {
-    echo "Запуск web-сервиса"
-    echo "!terra_colab_web [options]"
-    echo "    -h, --help    - Данная справочная информация"
-    echo "    -d, --dataset - Имя переменной экземпляра класса DTS"
-    echo ""
-    echo "Примеры"
-    echo "    1) !terra_colab_web -d=dataset"
-    echo "    2) !terra_colab_web --dataset=dataset"
-    echo "    3) !terra_colab_web"
-    echo "1) и 2) - запуск веб-сервиса с передачей датасета"
-    echo "3) - запуск веб-сервиса без передачи датасета"
-    echo ""
+  echo "Запуск web-сервиса"
+  echo "!terra_colab_web [options]"
+  echo "    -h, --help    - Данная справочная информация"
+  echo "    -d, --dataset - Имя переменной экземпляра класса DTS"
+  echo ""
+  echo "Примеры"
+  echo "    1) !terra_colab_web -d=dataset"
+  echo "    2) !terra_colab_web --dataset=dataset"
+  echo "    3) !terra_colab_web"
+  echo "1) и 2) - запуск веб-сервиса с передачей датасета"
+  echo "3) - запуск веб-сервиса без передачи датасета"
+  echo ""
 }
 
 while [ "$1" != "" ]; do
-    PARAM=$(echo $1 | awk -F= '{print $1}')
-    VALUE=$(echo $1 | awk -F= '{print $2}')
-    case $PARAM in
-        -h | --help)
-            usage
-            exit
-            ;;
-        -d | --dataset)
-            DATASET=$VALUE
-            ;;
-        *)
-            echo "${red}ERROR: unknown parameter \"$PARAM\"${reset}"
-            echo ""
-            usage
-            exit 1
-            ;;
-    esac
-    shift
+  PARAM=$(echo $1 | awk -F= '{print $1}')
+  VALUE=$(echo $1 | awk -F= '{print $2}')
+  case $PARAM in
+    -h | --help)
+      usage
+      exit
+      ;;
+    -d | --dataset)
+      DATASET=$VALUE
+      ;;
+    *)
+      echo "${red}ERROR: unknown parameter \"$PARAM\"${reset}"
+      echo ""
+      usage
+      exit 1
+      ;;
+  esac
+  shift
 done
 
 read -p "Введите E-mail: " EMAIL
@@ -50,6 +50,7 @@ if [ -z "$RESPONSE" ]; then
   rm -rf $TERRA_GUI_PATH
   git clone https://github.com/aiuniver/terra_gui.git $TERRA_GUI_PATH
   cd $TERRA_GUI_PATH || exit
+  pwd
   make
 else
   echo $RESPONSE
